version: '3.9'

services:
  web:
    build: ./LinkCounter
    container_name: django
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./LinkCounter/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - ./redis-data/:/data
volumes:
  redis-data:
    driver: local